<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hatchet</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Hatchet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*(#).*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.hatchet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.number-sign.hatchet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(@whitespace)(?:\s+(manual|inline|implicit))?\s*(.*?)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.hatchet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.hatchet</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.hatchet</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*([a-zA-Z_-]*)\s*:\s*(/.*$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.hatchet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.regexp.hatchet</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>"([^"\\]|\\.)*"</string>
			<key>name</key>
			<string>string.quoted.double.hatchet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_quoted_|_whitespace_)\b</string>
			<key>name</key>
			<string>keyword.hatchet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_-]+</string>
			<key>name</key>
			<string>variable.language.hatchet</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hatchet</string>
	<key>uuid</key>
	<string>0A1D9871-BBBB-11D9-BD50-000D93B6E43C</string>
</dict>
</plist>
